# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-16 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',)},
        ),
    ]
